on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Name of the environment to deploy to (DEV, QA, PROD)'
        required: true 

jobs:
  print_ENV:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        
      - name: Print environment input value
        run: echo "Environment selected:${{ github.event.inputs.environment }}"
        
        
      - name: envirnment value passing to reusable workflow 
        env:
          environment: ${{ github.event.inputs.environment }}
        uses: ./.github/workflows/testmain.yml        
        
        
#       - name: Deploy to environment
#         uses: ./.github/workflows/testmain.yml
#         with:
#          environment: ${{ github.event.inputs.environment }}
