---
# .github/workflows/main.yml
name: Main Workflow

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Name of the environment to deploy to (DEV, QA, PROD)'
        required: true 

jobs:
  my_job:
    runs-on: ubuntu-latest
    steps:
      - name: Print environment input value
        run: echo "Environment selected:${{ github.event.inputs.<input_name> }}"
  
