# This is my Mainworkflow

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Name of the environment to deploy to (DEV, QA, PROD)'
        required: true
env:
 INPUT_LOG_LEVEL: ${{ github.event.inputs.environment }}

jobs:
  call-workflow-passing-data:
    uses: ./.github/workflows/reuseable.yml
    with:
      environment: ${{ github.event.inputs.environment }}
