---
# .github/workflows/main.yml
name: Main Workflow

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Name of the environment to deploy to (DEV, QA, PROD)'
        required: true 

jobs:
  execute-ansible-playbook:
    name: Execute Ansible playbook
    uses: ./.github/workflows/helloword.yml
    secrets: inherit
