---
# .github/workflows/main.yml
name: Main Workflow

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Name of the environment to deploy to (DEV, QA, PROD)'
        required: true 

jobs:
  my_job:
    runs-on: ubuntu-latest
    steps:
      - name: Print environment input value
        run: echo "Environment selected:${{ github.event.inputs.environment }}"
      - name: envirnment value passing to reusable workflow
        uses: ./.github/workflows
        with:
          environment: ${{ github.event.inputs.environment }}
