# This is my reusable workflow

name: Deploy Workflow

on:
   workflow_call:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v1

      - name: Deploy to ${github.event.inputs.environment}
        run: |
          echo "Deploying to ${github.event.inputs.environment}"
