# This is my reusable worflow

on:
  workflow_call:
env:
  environment: ''

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    
     - name: Checkout Repository
       uses: actions/checkout@v1

     - name: Deploy to ${github.event.inputs.environment}
       run: |
         echo "Deploying to ${github.event.inputs.environment}"
