on:
  workflow_dispatch:
env:  
    environment: ${{ github.event.inputs.environment }}

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    
     - name: Checkout Repository
       uses: actions/checkout@v3

     - name: Deploy to ${inputs.environment}
       run: |
         echo "Deploying to ${inputs.environment}"
